### ISSUE TITLE
Missing .gitignore

### ISSUE THREAD

**Issue by torbentee** [aperkaz/telegram-unsplash-bot#1]
Hej @aperkaz I would recommend you to add an .gitignore to get rid of sth. like __pycache__ or .DS_Store

Your could use a tool like this [gitignore.io](https://www.gitignore.io/)

**Comment by aperkaz** [comment]
Thanks for the heads up @torbentee , ill add it. It is an automatic export from https://glitch.com , that is why is missing the gitignore 🙂

**Comment by aperkaz** [comment]
Update: The project has been cleaned up, and the gitignore added, @torbentee . Thanks for the heads up 🙂
